name: CI
on:
  schedule:
    - cron: '0 0 * * 0'
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: "adopt@1.11"
      - uses: coursier/cache-action@v6
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.TOKEN }}
          author-name: "20952117+keyno63-scala-steward[bot]@users.noreply.github.com"
          author-email: "author-email"
